language: python

sudo: enabled

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
script:
    - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  local-dir: docs
  repo: splab-ufcg/claret-site
  target_branch: master
  name: $GITHUB_NAME
  email: $GITHUB_EMAIL
  on:
    branch: master
