language: python

sudo: enabled

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.31.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
script:
    - hugo
