language: python

sudo: enabled

env:
  global:
    - GITHUB_REPO: "SPLAB-UFCG/claret-site"
    - secure: "MRHzG2vsYyB2BEOEPKK8cW7nu/feznSv+Qwp6Z9RV3aTe/zj6OG28qKUer+hik6PhgmMQSDqLgNbT1HsEqnqUHbINHWY4/3wSMi+f7dKzRhfPxz140JIPx4WM9wSyocfi7Mh1pQMJd3Z9qMkvooXYkCuj8SsKiHJ/4Y4Xc5ZDTPh6IfzekL5JFUUPNVjJxeq97gnSU9KepsIKE3uwJ01G1uc92T6+BPkqrpPUU/baEpuMFNGfo3JXPWAYoA16/QkwSsg+o2cxmLkWQbypnK6bY9mWS4GCOkxh5Lh8oyVX1TKEgp7HfDEPuq+CjVjROgYIcjFq0pei23MgN7eJIHfbyHbJB8LI5jg3X1DTLCdXjPs4tn1RXF+UhiDqKPuHh9VPqrj9k5JcVjPCpvHL7pHRxavzkfaXnO+2mDl/VDku8MufLw2JSuf4dvr8VoDk+by6RmDNEoAr9fNtIWKYoWFqiHXc/UpDx/zGqMBJMppUPUQQjr25urY07A9EonZqMGRx8m9Yni/5iUlcH5RZ1cpl5S8L9uECEhzIJq0sVESxVV4Rf23/cJ3S3rjJeZok+QHxSfj7oUuWs9sL8ksEzUwecmuduyFSOcSfHND2boik96di9JbcwQbnW1ARdwCYihHHWe+TOfaukTLLGJFsWAA8qAfBdlKin8sBboo3kNQm8s="

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments

script:
  - git remote -v
  - hugo

deploy:
  verbose: true
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: docs
  repo: splab-ufcg/claret-site
  target_branch: master
  on:
    branch: master
