baseURL = "http://example.org/"
languageCode = "en-us"
title = "CLARET"
theme = "hyde"

[params]
  themeColor = "theme-base-08"
  description = "Central Artifact for Requirements Engineering and Model-based Testing"